INSERT INTO CLOCK (MANUFACTURER, TYPE, COLOUR) VALUES('EuropeanStandardClocks', 'QUARTZ', 'Black');
INSERT INTO CLOCK (MANUFACTURER, TYPE, COLOUR) VALUES('EuropeanStandardClocks', 'QUARTZ', 'White');
INSERT INTO CLOCK (MANUFACTURER, TYPE, COLOUR) VALUES('EuropeanStandardClocks', 'QUARTZ', 'Blue');
INSERT INTO CLOCK (MANUFACTURER, TYPE, COLOUR) VALUES('AmericanAntique', 'MECHANICAL', 'Brown');
INSERT INTO CLOCK (MANUFACTURER, TYPE, COLOUR) VALUES('AmericanAntique', 'MECHANICAL', 'Grey');
INSERT INTO CLOCK (MANUFACTURER, TYPE, COLOUR) VALUES('ModernTime', 'QUARTZ', 'Pink');
INSERT INTO CLOCK (MANUFACTURER, TYPE, COLOUR) VALUES('ModernTime', 'QUARTZ', 'Cyan');